version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  grpc_server: # Nombre del servicio gRPC
    build:
      context: .
      dockerfile: Dockerfile.grpc # Apuntando a Dockerfile.grpc
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # ¡IMPORTANTE! Asegúrate de que no haya un volumen que monte ./app a /app
      - ./.env:/app/.env # Solo el .env
    command: python -u /app/app/app_grpc_server.py # Ruta correcta al script

  envoy:
    image: envoyproxy/envoy:v1.22.0
    restart: always
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
      - "9901:9901"
    depends_on:
      grpc_server: # Depende del servicio gRPC
        condition: service_started

volumes:
  postgres_data:
