# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import productos_pb2 as productos__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in productos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductosServiceStub(object):
    """Definición del servicio gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProducto = channel.unary_unary(
                '/productos_service.ProductosService/CreateProducto',
                request_serializer=productos__pb2.CreateProductoRequest.SerializeToString,
                response_deserializer=productos__pb2.ProductoResponse.FromString,
                _registered_method=True)
        self.GetProducto = channel.unary_unary(
                '/productos_service.ProductosService/GetProducto',
                request_serializer=productos__pb2.GetProductoRequest.SerializeToString,
                response_deserializer=productos__pb2.ProductoResponse.FromString,
                _registered_method=True)
        self.ListProductos = channel.unary_unary(
                '/productos_service.ProductosService/ListProductos',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=productos__pb2.ListProductosResponse.FromString,
                _registered_method=True)
        self.CreateSucursal = channel.unary_unary(
                '/productos_service.ProductosService/CreateSucursal',
                request_serializer=productos__pb2.CreateSucursalRequest.SerializeToString,
                response_deserializer=productos__pb2.SucursalResponse.FromString,
                _registered_method=True)
        self.GetSucursal = channel.unary_unary(
                '/productos_service.ProductosService/GetSucursal',
                request_serializer=productos__pb2.GetSucursalRequest.SerializeToString,
                response_deserializer=productos__pb2.SucursalResponse.FromString,
                _registered_method=True)
        self.ListSucursales = channel.unary_unary(
                '/productos_service.ProductosService/ListSucursales',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=productos__pb2.ListSucursalesResponse.FromString,
                _registered_method=True)
        self.AddStock = channel.unary_unary(
                '/productos_service.ProductosService/AddStock',
                request_serializer=productos__pb2.AddStockRequest.SerializeToString,
                response_deserializer=productos__pb2.StockResponse.FromString,
                _registered_method=True)
        self.RemoveStock = channel.unary_unary(
                '/productos_service.ProductosService/RemoveStock',
                request_serializer=productos__pb2.RemoveStockRequest.SerializeToString,
                response_deserializer=productos__pb2.StockResponse.FromString,
                _registered_method=True)
        self.UpdateStock = channel.unary_unary(
                '/productos_service.ProductosService/UpdateStock',
                request_serializer=productos__pb2.UpdateStockRequest.SerializeToString,
                response_deserializer=productos__pb2.StockResponse.FromString,
                _registered_method=True)
        self.GetStock = channel.unary_unary(
                '/productos_service.ProductosService/GetStock',
                request_serializer=productos__pb2.GetStockRequest.SerializeToString,
                response_deserializer=productos__pb2.StockResponse.FromString,
                _registered_method=True)
        self.ListStockByProduct = channel.unary_unary(
                '/productos_service.ProductosService/ListStockByProduct',
                request_serializer=productos__pb2.ListStockByProductRequest.SerializeToString,
                response_deserializer=productos__pb2.ListStockByProductResponse.FromString,
                _registered_method=True)
        self.ListStockByBranch = channel.unary_unary(
                '/productos_service.ProductosService/ListStockByBranch',
                request_serializer=productos__pb2.ListStockByBranchRequest.SerializeToString,
                response_deserializer=productos__pb2.ListStockByBranchResponse.FromString,
                _registered_method=True)


class ProductosServiceServicer(object):
    """Definición del servicio gRPC
    """

    def CreateProducto(self, request, context):
        """RPCs para Productos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProductos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSucursal(self, request, context):
        """RPCs para Sucursales
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSucursal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSucursales(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStock(self, request, context):
        """RPCs para Stock de Productos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStockByProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStockByBranch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProducto,
                    request_deserializer=productos__pb2.CreateProductoRequest.FromString,
                    response_serializer=productos__pb2.ProductoResponse.SerializeToString,
            ),
            'GetProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProducto,
                    request_deserializer=productos__pb2.GetProductoRequest.FromString,
                    response_serializer=productos__pb2.ProductoResponse.SerializeToString,
            ),
            'ListProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProductos,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=productos__pb2.ListProductosResponse.SerializeToString,
            ),
            'CreateSucursal': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSucursal,
                    request_deserializer=productos__pb2.CreateSucursalRequest.FromString,
                    response_serializer=productos__pb2.SucursalResponse.SerializeToString,
            ),
            'GetSucursal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSucursal,
                    request_deserializer=productos__pb2.GetSucursalRequest.FromString,
                    response_serializer=productos__pb2.SucursalResponse.SerializeToString,
            ),
            'ListSucursales': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSucursales,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=productos__pb2.ListSucursalesResponse.SerializeToString,
            ),
            'AddStock': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStock,
                    request_deserializer=productos__pb2.AddStockRequest.FromString,
                    response_serializer=productos__pb2.StockResponse.SerializeToString,
            ),
            'RemoveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveStock,
                    request_deserializer=productos__pb2.RemoveStockRequest.FromString,
                    response_serializer=productos__pb2.StockResponse.SerializeToString,
            ),
            'UpdateStock': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStock,
                    request_deserializer=productos__pb2.UpdateStockRequest.FromString,
                    response_serializer=productos__pb2.StockResponse.SerializeToString,
            ),
            'GetStock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStock,
                    request_deserializer=productos__pb2.GetStockRequest.FromString,
                    response_serializer=productos__pb2.StockResponse.SerializeToString,
            ),
            'ListStockByProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStockByProduct,
                    request_deserializer=productos__pb2.ListStockByProductRequest.FromString,
                    response_serializer=productos__pb2.ListStockByProductResponse.SerializeToString,
            ),
            'ListStockByBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStockByBranch,
                    request_deserializer=productos__pb2.ListStockByBranchRequest.FromString,
                    response_serializer=productos__pb2.ListStockByBranchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'productos_service.ProductosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('productos_service.ProductosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductosService(object):
    """Definición del servicio gRPC
    """

    @staticmethod
    def CreateProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/CreateProducto',
            productos__pb2.CreateProductoRequest.SerializeToString,
            productos__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/GetProducto',
            productos__pb2.GetProductoRequest.SerializeToString,
            productos__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/ListProductos',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            productos__pb2.ListProductosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSucursal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/CreateSucursal',
            productos__pb2.CreateSucursalRequest.SerializeToString,
            productos__pb2.SucursalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSucursal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/GetSucursal',
            productos__pb2.GetSucursalRequest.SerializeToString,
            productos__pb2.SucursalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSucursales(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/ListSucursales',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            productos__pb2.ListSucursalesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/AddStock',
            productos__pb2.AddStockRequest.SerializeToString,
            productos__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/RemoveStock',
            productos__pb2.RemoveStockRequest.SerializeToString,
            productos__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/UpdateStock',
            productos__pb2.UpdateStockRequest.SerializeToString,
            productos__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/GetStock',
            productos__pb2.GetStockRequest.SerializeToString,
            productos__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStockByProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/ListStockByProduct',
            productos__pb2.ListStockByProductRequest.SerializeToString,
            productos__pb2.ListStockByProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStockByBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos_service.ProductosService/ListStockByBranch',
            productos__pb2.ListStockByBranchRequest.SerializeToString,
            productos__pb2.ListStockByBranchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
