syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

package productos_service;

// Mensaje para un Producto
message Producto {
  int32 id = 1;
  string nombre = 2;
  string descripcion = 3;
  bytes imagen = 4;
}

// Mensaje para una Sucursal
message Sucursal {
  int32 id = 1;
  string nombre = 2;
  string direccion = 3;
}

// Mensaje para el Stock de un Producto en una Sucursal específica
message StockProducto {
  int32 id = 1;
  int32 id_sucursal = 2;
  int32 id_producto = 3;
  int32 cantidad = 4;
  double precio = 5;
}

// Mensaje para una Venta
message Venta {
  int32 id = 1;
  google.protobuf.Timestamp fecha = 2;
  double total_venta = 3;
  int32 id_sucursal = 4;
}

// Mensaje para los Detalles de Venta
message DetalleVenta {
  int32 id = 1;
  int32 id_venta = 2;
  int32 id_producto = 3;
  int32 cantidad = 4;
  double precio_unitario = 5;
}


// Solicitudes y Respuestas para Productos
message CreateProductoRequest {
  string nombre = 1;
  string descripcion = 2;
  bytes imagen = 3;
}

message ProductoResponse {
  Producto producto = 1;
  string message = 2;
  bool success = 3;
}

message GetProductoRequest {
  int32 id = 1;
}

message ListProductosResponse {
  repeated Producto productos = 1;
}


// Solicitudes y Respuestas para Sucursales
message CreateSucursalRequest {
  string nombre = 1;
  string direccion = 2;
}

message SucursalResponse {
  Sucursal sucursal = 1;
  string message = 2;
  bool success = 3;
}

message GetSucursalRequest {
  int32 id = 1;
}

message ListSucursalesResponse {
  repeated Sucursal sucursales = 1;
}


// Solicitudes y Respuestas para Stock de Productos
message AddStockRequest {
  int32 id_producto = 1;
  int32 id_sucursal = 2;
  int32 cantidad_a_sumar = 3;
}

message RemoveStockRequest {
  int32 id_producto = 1;
  int32 id_sucursal = 2;
  int32 cantidad_a_restar = 3;
}

message UpdateStockRequest {
  int32 id_producto = 1;
  int32 id_sucursal = 2;
  int32 nueva_cantidad = 3;
  double nuevo_precio = 4;
}

message GetStockRequest {
  int32 id_producto = 1;
  int32 id_sucursal = 2;
}

message StockResponse {
  StockProducto stock_producto = 1;
  string message = 2;
  bool success = 3;
}

message ListStockByProductRequest {
  int32 id_producto = 1;
}

message ListStockByProductResponse {
  repeated StockProducto stock_productos = 1;
}

message ListStockByBranchRequest {
  int32 id_sucursal = 1;
}

message ListStockByBranchResponse {
  repeated StockProducto stock_productos = 1;
}


// Definición del servicio gRPC
service ProductosService {
  // RPCs para Productos
  rpc CreateProducto (CreateProductoRequest) returns (ProductoResponse);
  rpc GetProducto (GetProductoRequest) returns (ProductoResponse);
  rpc ListProductos (google.protobuf.Empty) returns (ListProductosResponse);

  // RPCs para Sucursales
  rpc CreateSucursal (CreateSucursalRequest) returns (SucursalResponse);
  rpc GetSucursal (GetSucursalRequest) returns (SucursalResponse);
  rpc ListSucursales (google.protobuf.Empty) returns (ListSucursalesResponse);

  // RPCs para Stock de Productos
  rpc AddStock (AddStockRequest) returns (StockResponse);
  rpc RemoveStock (RemoveStockRequest) returns (StockResponse);
  rpc UpdateStock (UpdateStockRequest) returns (StockResponse);
  rpc GetStock (GetStockRequest) returns (StockResponse);
  rpc ListStockByProduct (ListStockByProductRequest) returns (ListStockByProductResponse);
  rpc ListStockByBranch (ListStockByBranchRequest) returns (ListStockByBranchResponse);
}
