/**
 * @fileoverview gRPC-Web generated client stub for productos_service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: productos.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as productos_pb from './productos_pb'; // proto import: "productos.proto"


export class ProductosServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateProducto = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/CreateProducto',
    grpcWeb.MethodType.UNARY,
    productos_pb.CreateProductoRequest,
    productos_pb.ProductoResponse,
    (request: productos_pb.CreateProductoRequest) => {
      return request.serializeBinary();
    },
    productos_pb.ProductoResponse.deserializeBinary
  );

  createProducto(
    request: productos_pb.CreateProductoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.ProductoResponse>;

  createProducto(
    request: productos_pb.CreateProductoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.ProductoResponse) => void): grpcWeb.ClientReadableStream<productos_pb.ProductoResponse>;

  createProducto(
    request: productos_pb.CreateProductoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.ProductoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/CreateProducto',
        request,
        metadata || {},
        this.methodDescriptorCreateProducto,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/CreateProducto',
    request,
    metadata || {},
    this.methodDescriptorCreateProducto);
  }

  methodDescriptorGetProducto = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/GetProducto',
    grpcWeb.MethodType.UNARY,
    productos_pb.GetProductoRequest,
    productos_pb.ProductoResponse,
    (request: productos_pb.GetProductoRequest) => {
      return request.serializeBinary();
    },
    productos_pb.ProductoResponse.deserializeBinary
  );

  getProducto(
    request: productos_pb.GetProductoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.ProductoResponse>;

  getProducto(
    request: productos_pb.GetProductoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.ProductoResponse) => void): grpcWeb.ClientReadableStream<productos_pb.ProductoResponse>;

  getProducto(
    request: productos_pb.GetProductoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.ProductoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/GetProducto',
        request,
        metadata || {},
        this.methodDescriptorGetProducto,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/GetProducto',
    request,
    metadata || {},
    this.methodDescriptorGetProducto);
  }

  methodDescriptorListProductos = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/ListProductos',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    productos_pb.ListProductosResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    productos_pb.ListProductosResponse.deserializeBinary
  );

  listProductos(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.ListProductosResponse>;

  listProductos(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.ListProductosResponse) => void): grpcWeb.ClientReadableStream<productos_pb.ListProductosResponse>;

  listProductos(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.ListProductosResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/ListProductos',
        request,
        metadata || {},
        this.methodDescriptorListProductos,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/ListProductos',
    request,
    metadata || {},
    this.methodDescriptorListProductos);
  }

  methodDescriptorCreateSucursal = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/CreateSucursal',
    grpcWeb.MethodType.UNARY,
    productos_pb.CreateSucursalRequest,
    productos_pb.SucursalResponse,
    (request: productos_pb.CreateSucursalRequest) => {
      return request.serializeBinary();
    },
    productos_pb.SucursalResponse.deserializeBinary
  );

  createSucursal(
    request: productos_pb.CreateSucursalRequest,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.SucursalResponse>;

  createSucursal(
    request: productos_pb.CreateSucursalRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.SucursalResponse) => void): grpcWeb.ClientReadableStream<productos_pb.SucursalResponse>;

  createSucursal(
    request: productos_pb.CreateSucursalRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.SucursalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/CreateSucursal',
        request,
        metadata || {},
        this.methodDescriptorCreateSucursal,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/CreateSucursal',
    request,
    metadata || {},
    this.methodDescriptorCreateSucursal);
  }

  methodDescriptorGetSucursal = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/GetSucursal',
    grpcWeb.MethodType.UNARY,
    productos_pb.GetSucursalRequest,
    productos_pb.SucursalResponse,
    (request: productos_pb.GetSucursalRequest) => {
      return request.serializeBinary();
    },
    productos_pb.SucursalResponse.deserializeBinary
  );

  getSucursal(
    request: productos_pb.GetSucursalRequest,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.SucursalResponse>;

  getSucursal(
    request: productos_pb.GetSucursalRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.SucursalResponse) => void): grpcWeb.ClientReadableStream<productos_pb.SucursalResponse>;

  getSucursal(
    request: productos_pb.GetSucursalRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.SucursalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/GetSucursal',
        request,
        metadata || {},
        this.methodDescriptorGetSucursal,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/GetSucursal',
    request,
    metadata || {},
    this.methodDescriptorGetSucursal);
  }

  methodDescriptorListSucursales = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/ListSucursales',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    productos_pb.ListSucursalesResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    productos_pb.ListSucursalesResponse.deserializeBinary
  );

  listSucursales(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.ListSucursalesResponse>;

  listSucursales(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.ListSucursalesResponse) => void): grpcWeb.ClientReadableStream<productos_pb.ListSucursalesResponse>;

  listSucursales(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.ListSucursalesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/ListSucursales',
        request,
        metadata || {},
        this.methodDescriptorListSucursales,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/ListSucursales',
    request,
    metadata || {},
    this.methodDescriptorListSucursales);
  }

  methodDescriptorAddStock = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/AddStock',
    grpcWeb.MethodType.UNARY,
    productos_pb.AddStockRequest,
    productos_pb.StockResponse,
    (request: productos_pb.AddStockRequest) => {
      return request.serializeBinary();
    },
    productos_pb.StockResponse.deserializeBinary
  );

  addStock(
    request: productos_pb.AddStockRequest,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.StockResponse>;

  addStock(
    request: productos_pb.AddStockRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.StockResponse) => void): grpcWeb.ClientReadableStream<productos_pb.StockResponse>;

  addStock(
    request: productos_pb.AddStockRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.StockResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/AddStock',
        request,
        metadata || {},
        this.methodDescriptorAddStock,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/AddStock',
    request,
    metadata || {},
    this.methodDescriptorAddStock);
  }

  methodDescriptorRemoveStock = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/RemoveStock',
    grpcWeb.MethodType.UNARY,
    productos_pb.RemoveStockRequest,
    productos_pb.StockResponse,
    (request: productos_pb.RemoveStockRequest) => {
      return request.serializeBinary();
    },
    productos_pb.StockResponse.deserializeBinary
  );

  removeStock(
    request: productos_pb.RemoveStockRequest,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.StockResponse>;

  removeStock(
    request: productos_pb.RemoveStockRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.StockResponse) => void): grpcWeb.ClientReadableStream<productos_pb.StockResponse>;

  removeStock(
    request: productos_pb.RemoveStockRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.StockResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/RemoveStock',
        request,
        metadata || {},
        this.methodDescriptorRemoveStock,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/RemoveStock',
    request,
    metadata || {},
    this.methodDescriptorRemoveStock);
  }

  methodDescriptorUpdateStock = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/UpdateStock',
    grpcWeb.MethodType.UNARY,
    productos_pb.UpdateStockRequest,
    productos_pb.StockResponse,
    (request: productos_pb.UpdateStockRequest) => {
      return request.serializeBinary();
    },
    productos_pb.StockResponse.deserializeBinary
  );

  updateStock(
    request: productos_pb.UpdateStockRequest,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.StockResponse>;

  updateStock(
    request: productos_pb.UpdateStockRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.StockResponse) => void): grpcWeb.ClientReadableStream<productos_pb.StockResponse>;

  updateStock(
    request: productos_pb.UpdateStockRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.StockResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/UpdateStock',
        request,
        metadata || {},
        this.methodDescriptorUpdateStock,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/UpdateStock',
    request,
    metadata || {},
    this.methodDescriptorUpdateStock);
  }

  methodDescriptorGetStock = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/GetStock',
    grpcWeb.MethodType.UNARY,
    productos_pb.GetStockRequest,
    productos_pb.StockResponse,
    (request: productos_pb.GetStockRequest) => {
      return request.serializeBinary();
    },
    productos_pb.StockResponse.deserializeBinary
  );

  getStock(
    request: productos_pb.GetStockRequest,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.StockResponse>;

  getStock(
    request: productos_pb.GetStockRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.StockResponse) => void): grpcWeb.ClientReadableStream<productos_pb.StockResponse>;

  getStock(
    request: productos_pb.GetStockRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.StockResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/GetStock',
        request,
        metadata || {},
        this.methodDescriptorGetStock,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/GetStock',
    request,
    metadata || {},
    this.methodDescriptorGetStock);
  }

  methodDescriptorListStockByProduct = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/ListStockByProduct',
    grpcWeb.MethodType.UNARY,
    productos_pb.ListStockByProductRequest,
    productos_pb.ListStockByProductResponse,
    (request: productos_pb.ListStockByProductRequest) => {
      return request.serializeBinary();
    },
    productos_pb.ListStockByProductResponse.deserializeBinary
  );

  listStockByProduct(
    request: productos_pb.ListStockByProductRequest,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.ListStockByProductResponse>;

  listStockByProduct(
    request: productos_pb.ListStockByProductRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.ListStockByProductResponse) => void): grpcWeb.ClientReadableStream<productos_pb.ListStockByProductResponse>;

  listStockByProduct(
    request: productos_pb.ListStockByProductRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.ListStockByProductResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/ListStockByProduct',
        request,
        metadata || {},
        this.methodDescriptorListStockByProduct,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/ListStockByProduct',
    request,
    metadata || {},
    this.methodDescriptorListStockByProduct);
  }

  methodDescriptorListStockByBranch = new grpcWeb.MethodDescriptor(
    '/productos_service.ProductosService/ListStockByBranch',
    grpcWeb.MethodType.UNARY,
    productos_pb.ListStockByBranchRequest,
    productos_pb.ListStockByBranchResponse,
    (request: productos_pb.ListStockByBranchRequest) => {
      return request.serializeBinary();
    },
    productos_pb.ListStockByBranchResponse.deserializeBinary
  );

  listStockByBranch(
    request: productos_pb.ListStockByBranchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<productos_pb.ListStockByBranchResponse>;

  listStockByBranch(
    request: productos_pb.ListStockByBranchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: productos_pb.ListStockByBranchResponse) => void): grpcWeb.ClientReadableStream<productos_pb.ListStockByBranchResponse>;

  listStockByBranch(
    request: productos_pb.ListStockByBranchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: productos_pb.ListStockByBranchResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/productos_service.ProductosService/ListStockByBranch',
        request,
        metadata || {},
        this.methodDescriptorListStockByBranch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/productos_service.ProductosService/ListStockByBranch',
    request,
    metadata || {},
    this.methodDescriptorListStockByBranch);
  }

}

